# +-----------+
# |           |
# |  PLUMBER  |
# |           |
# +-----------+

if (requireNamespace("renv", quietly = TRUE)) {
  if (is.null(renv::project())) {
    renv::activate()
  }
  message("Renv already activated")
}

readRenviron(".Renviron")

source("R/utils/libraries.R", chdir = TRUE)
source("R/utils/env_setup.R", chdir = TRUE)
source("R/utils/auth-filter.R", chdir = TRUE)
source("R/utils/database_pool_setup.R", chdir = TRUE)

# +-------------------------------------+
# |     PACKAGES AND INITIAL CONFIG     |
# +-------------------------------------+

# Configuring parallelism using multisession to maintain Windows Compatibility
future::plan(future::multisession, workers = parallel::detectCores() - 1)

# Create an object that represents a empty plumber API
pr <- plumber::pr()

# +-------------------------------------+
# |  GLOBAL MIDDLEWARE CONFIGURATION    |
# +-------------------------------------+

# ADD CORS Filter globally
pr <- pr %>%
  pr_filter("cors", function(req, res) {
    res$setHeader("Access-Control-Allow-Origin", "*")
    plumber::forward()
  }) %>%
  pr_hook("exit", function() {
    close_all_pools()
  })

# +-------------------------------------+
# |     ENDPOINTS ROUTER CREATION       |
# +-------------------------------------+

# Define the route paths
route_paths <- c(
  account = "R/controllers/account.R",
  analytics = "R/controllers/analytics.R",
  anomaly_detection = "R/controllers/anomaly-detection.R",
  category = "R/controllers/category.R",
  esp32_data_entry = "R/controllers/esp32-data-entry.R",
  location = "R/controllers/location.R",
  products = "R/controllers/products.R",
  solar_cell = "R/controllers/solar-cell.R",
  statistics = "R/controllers/statistics.R",
  status = "R/controllers/status.R",
  time_series = "R/controllers/time-series.R",
  user = "R/controllers/user.R"
)

# Create a named list of routers
routers <- setNames(lapply(route_paths, plumber::plumb), names(route_paths))

# +-------------------------------------+
# |    FILTER ADDITION TO ENDPOINTS     |
# +-------------------------------------+

# Apply authentication filter only to specific routers
routers$anomaly_detection <- routers$anomaly_detection %>%
  pr_filter("authenticate", authenticate)
routers$user <- routers$user %>%
  pr_filter("authenticate", authenticate)
routers$solar_cell <- routers$solar_cell %>%
  pr_filter("authenticate", authenticate)
routers$statistics <- routers$statistics %>%
  pr_filter("authenticate", authenticate)
routers$time_series <- routers$time_series %>%
  pr_filter("authenticate", authenticate)

# +-------------------------------------+
# |        MOUNTING ENDPOINTS           |
# +-------------------------------------+

pr$mount("/Account", routers$account)                      # No authentication required
pr$mount("/Anomaly_Detection", routers$anomaly_detection)  # Requires authentication
pr$mount("/User", routers$user)                            # Requires authentication
pr$mount("/Solar_Cell", routers$solar_cell)                # Requires authentication
pr$mount("/Statistics", routers$statistics)                # Requires authentication
pr$mount("/Time_Series", routers$time_series)              # Requires authentication
pr$mount("/Category", routers$category)                    # No authentication required
pr$mount("/Location", routers$location)                    # No authentication required
pr$mount("/Products", routers$products)                    # No authentication required
pr$mount("/Analytics", routers$analytics)                  # No authentication required
pr$mount("/ESP32_DataEntry", routers$esp32_data_entry)     # No authentication required
pr$mount("/Status", routers$status)                        # No authentication required

# +-------------------------------------+
# |      DOCUMENTATION SETTINGS         |
# +-------------------------------------+

pr <- pr %>% pr_set_api_spec(function(spec) {
  spec$components$securitySchemes$bearerAuth <- list(
    type = "http",
    scheme = "bearer",
    bearerFormat = "JWT"
  )

  spec$security <- list(list(bearerAuth = list()))

  # Specifies one specific endpoint to surpass the authentication
  spec$paths$`/Account/register`$get$security <- NULL
  spec$paths$`/Account/login`$get$security <- NULL
  spec$paths$`/Status/ping`$get$security <- NULL
  spec$path$`/ESP32_DataEntry/send_data/solar_panel`$get$security <- NULL

  spec$info$title <- "Solar Panel One API"
  spec$info$description <- "This API is constructed using the R Language and the packages Plumber, and it is designated to work beside the system of solar panels \"One\" that uses ESP32. The objective is to make queries on the database, analyze and process the data generated by the system and plot them with it interactive warnings depending on the variations of the data."

  spec
})

pr$setDocs(TRUE)

# +-------------------------------------+
# |  RUNNING THE API AND SETTING PORT   |
# +-------------------------------------+

pr$run(host = "0.0.0.0", port = 8000)